local: &local
  adapter: postgresql
  username: crud_post
  password: crud_post
  host: localhost
development:
  <<: *local
  database: crud_post_development
test:
  <<: *local
  database: crud_post_test
production:
  <<: *local
  database: crud_post_production
